### ISSUE TITLE
feat: Cairo Variables

### ISSUE THREAD

**Issue by enitrat** [NethermindEth/CairoByExample#1]
This example will introduce the three types of variables commonly found in Cairo contracts:
- Local variables, who are declared inside a function and not stored on the blockchain
- Storage variables, declared in the `Storage` struct, stored on the blockchain and that can be accessed from one execution to another
- global variables, who provide information about the blockchain and are accessed with library functions: `get_caller_address`, `get_contract_address`,  etc...

Solidity reference: https://solidity-by-example.org/variables/

**Comment by julio4** [comment]
Can you assign me?
