### ISSUE TITLE
feat: Mappings in contracts

### ISSUE THREAD

**Issue by enitrat** [NethermindEth/CairoByExample#2]
A basic contract that demonstrates how to use the `LegacyMap` type to store mappings in storage.
This example will also demonstrate how to create mappings with multiple keys.

Solidity reference: https://solidity-by-example.org/mapping/

**Comment by rianhughes** [comment]
Hey, I would like to work on this.

**Comment by rianhughes** [comment]
https://github.com/rianhughes/CairoByExample/tree/map

**Comment by enitrat** [comment]
Hey @rianhughes Can you create a PR to the main branch of this repository?

**Comment by enitrat** [comment]
Closed by #33
