### ISSUE TITLE
feat: Errors

### ISSUE THREAD

**Issue by enitrat** [NethermindEth/CairoByExample#6]
In this example, we will introduce errors and how we can throw them during the execution of a contract, undoing all changes made during the transaction.
- The `assert` corelib function can be used to check a boolean condition and return an error message if it fails.
- The `panic` corelib function can be used to stop the execution of a program and return an error message.

Solidity reference: https://solidity-by-example.org/error/

**Comment by julio4** [comment]
I can take this one.
